# This module will create a binarized datasets
# for consumption by fairseq. The default implementation
# is mmap. This also will apply an SPM model if you
# have one specified.

# The disitllation_pipeline expects to find a dict.{lang}.txt
# in the spm_model_path/data_bin/shard000/ path.

vocab_file_path: ${vocab_file_path}
spm_model_path: ${spm_model_path}
outfile_prefix: ${.line_processor.dataset_impl}_ds
custom_name: FairSeqBinarizerEncoder

buffer_size: 10_000
output_dir: .
line_processor:
  _target_: stopes.modules.preprocess.fairseq_binarizer_encoder.FairSeqBinarizerEncoder
  vocab_file_path: ${..vocab_file_path}
  spm_model_path: ${..spm_model_path}
  dataset_impl: mmap
requirements:
  nodes: 1
  tasks_per_node: 1
  gpus_per_node: 1
  cpus_per_task: 4
  timeout_min: 240
