defaults:
  - launcher: submitit
  - _self_

output_dir: ???
use_gpu: true
batch_size: 16

src_manifest: ???
tgt_manifest: ???
ref_manifest: null

src_lang: ???
tgt_lang: ???
# by default tgt and ref are the same lang
ref_lang: ${tgt_lang}

checkpoint_dir: ???

# where to find the blaser model, you can find it at http://dl.fbaipublicfiles.com/blaser/blaser.tar.gz
blaser_model:
  config_file: ???
  model_checkpoint: ???

max_tokens: 2_560_000

checkpoints:
  en: english.pt
  ru: slavic.pt
  cs: slavic.pt
  pl: slavic.pt
  sk: slavic.pt
  hr: slavic.pt
  ca: romance.pt
  es: romance.pt
  fr: romance.pt
  it: romance.pt
  pt: romance.pt
  ro: romance.pt
  de: germanic.pt
  cmn: mandarin.pt
