# This module will create a binarized datasets
# for consumption by fairseq. The default implementation
# is mmap. This also will apply an SPM model if you
# have one specified.

_target_: stopes.modules.preprocess.line_processor.LineProcessorModule
config:
  vocab_file_path: ???
  spm_model_path: null
  outfile_prefix: ${.line_processor.dataset_impl}_ds
  output_dir: .
  custom_name: FairSeqBinarizerEncoder
  shards: ???
  buffer_size: 10_000
  line_processor:
    _target_: stopes.modules.preprocess.fairseq_binarizer_encoder.FairSeqBinarizerEncoder
    vocab_file_path: ${..vocab_file_path}
    spm_model_path: ${..spm_model_path}
    dataset_impl: mmap
  requirements:
    nodes: 1
    tasks_per_node: 1
    gpus_per_node: 1
    cpus_per_task: 4
    timeout_min: 240
