custom_name: FairSeqBinarizerEncoder
shards: ???
output_dir: ???
buffer_size: 10_000
line_processor:
  _target_: stopes.modules.preprocess.fairseq_binarizer_encoder.FairSeqBinarizerEncoder
  dataset_impl: mmap
requirements:
  nodes: 1
  tasks_per_node: 1
  gpus_per_node: 1
  cpus_per_task: 4
  timeout_min: 240
