_target_: stopes.modules.preprocess.preprocess_encode_module.PreprocessEncodeModule

defaults:
  - config: standard_conf
  - config/preprocess: moses

config:
  preprocess:
    output_dir: ${..output_dir}/moses_preprocess
    shards: ${..shards}
    lang: ${..lang}
